package de.pxlab.pxl;

/**
 * Describes color coordinates change events. These are created whenever a color
 * source component creates changes in the coordinates of a target color.
 * Possible sources are ColorCoordinatePanels and ColorAdjustmentPanels.
 * 
 * @author H. Irtel
 * @version 0.2.0
 * @see ColorServer
 * @see ColorChangeListener
 */
public class ColorChangeEvent extends PxlEvent {
	/**
	 * Event type generated whenever someone has adjusted the currently active
	 * color of the color server.
	 */
	public static final int COLOR_ADJUSTED = COLOR_CHANGE_EVENT_FIRST + 0;
	/**
	 * Event type generated by a color server's setActiveColor() method being
	 * called.
	 */
	public static final int COLOR_SET = COLOR_CHANGE_EVENT_FIRST + 1;
	/**
	 * Event type generated by a color server's setActiveColor() method being
	 * called and the color change listeners should switch into passive display
	 * mode.
	 */
	public static final int COLOR_SET_PASSIVE = COLOR_CHANGE_EVENT_FIRST + 2;
	private PxlColor color;

	/** Create a new ColorChangeEvent. */
	public ColorChangeEvent(Object s, int i, PxlColor c) {
		super(s, i);
		color = c;
	}

	/** Return this event's color. */
	public PxlColor getColor() {
		return (color);
	}

	/** Return a text description of this event. */
	public String toString() {
		return (getClass().getName() + " [id=" + getID() + ", color="
				+ color.toString() + "] on " + getSource());
	}
}
