package de.pxlab.pxl;

/**
 * Describes events generated by an external control box.
 * 
 * @author H. Irtel
 * @version 0.1.0
 * @see ExternalControlBox
 * @see ExternalButtonListener
 */
public class ExternalButtonEvent extends java.util.EventObject {
	private int buttonCode;
	private long when;

	public ExternalButtonEvent(Object source, long when, int code) {
		super(source);
		this.when = when;
		buttonCode = code;
	}

	public long getWhen() {
		return when;
	}

	public int getButtonCode() {
		return buttonCode;
	}
}
