package de.pxlab.pxl;

/**
 * Describes objects which listen to events generated by an external button box.
 * 
 * @author H. Irtel
 * @version 0.1.0
 */
public interface ExternalButtonListener {
	/** Invoked when an external response box button has been pressed. */
	public void externalButtonPressed(ExternalButtonEvent e);

	/** Invoked when an external response box button has been released. */
	public void externalButtonReleased(ExternalButtonEvent e);
}
