package de.pxlab.pxl;

/**
 * An ActionEvent event generated by a media controller.
 * 
 * @version 0.3.1
 */
public class MediaEvent extends java.awt.event.ActionEvent {
	/**
	 * Media time when the event happened. If the event happened before the the
	 * media time starts then this is a negative number whose value is
	 * meaningless. The time is stored in nanoseconds.
	 */
	private long mediaTime = 0L;

	/**
	 * Create a MediaEvent object.
	 * 
	 * @param source
	 *            the source of the event.
	 * @param id
	 *            the media event id. Possible ID codes are defined earlier in
	 *            this file.
	 * @param mt
	 *            the media time of the event in nanoseconds. This time is
	 *            relative to the media start.
	 * @param when
	 *            the absolute time of the event in milliseconds.
	 */
	public MediaEvent(Object source, int id, long mt, long when) {
		super(source, id, "Media Event", when, 0);
		mediaTime = mt;
	}

	/**
	 * Return the media time of this event. If the event happened before the the
	 * media time starts then this is a negative number whose value is
	 * meaningless.
	 * 
	 * @return the time of the event in nanoseconds relative to the media time
	 *         base. Note that the media time starts when the media controller
	 *         starts.
	 */
	public long getMediaTimeNanos() {
		return mediaTime;
	}

	/**
	 * Return the media time of this event. If the event happened before the the
	 * media time starts then this is a negative number whose value is
	 * meaningless.
	 * 
	 * @return the time of the event in milliseconds relative to the media time
	 *         base. Note that the media time starts when the media controller
	 *         starts.
	 */
	public long getMediaTime() {
		return Math.round(((double) mediaTime) / 1000000.0);
	}
}
