package de.pxlab.pxl;

/**
 * Describes events generated by a serial text input device which is capable of
 * sending lines of text.
 * 
 * @author H. Irtel
 * @version 0.1.0
 */
public class SerialLineInputEvent extends java.util.EventObject {
	private String text;
	private long when;

	public SerialLineInputEvent(Object source, long when, String text) {
		super(source);
		this.when = when;
		this.text = text;
	}

	public long getWhen() {
		return when;
	}

	public String getText() {
		return text;
	}
}
