/* Generated By:JavaCC: Do not edit this line. ExDesignTreeParserConstants.java */
package de.pxlab.pxl.parser;

public interface ExDesignTreeParserConstants {
	int EOF = 0;
	int SINGLE_LINE_COMMENT = 9;
	int FORMAL_COMMENT = 10;
	int MULTI_LINE_COMMENT = 11;
	int EXPERIMENT = 13;
	int EXPERIMENTDATA = 14;
	int PROCEDURE = 15;
	int PROCEDUREEND = 16;
	int PROCEDUREDATA = 17;
	int SESSION = 18;
	int SESSIONEND = 19;
	int SESSIONDATA = 20;
	int BLOCK = 21;
	int BLOCKEND = 22;
	int BLOCKDATA = 23;
	int TRIAL = 24;
	int TRIALDATA = 25;
	int NEWPAR = 26;
	int ADJUSTABLE = 27;
	int CONTEXT = 28;
	int ASSIGNMENTGROUP = 29;
	int CONTINUATIONGROUP = 30;
	int FACTORS = 31;
	int RANDFACTOR = 32;
	int INDEPFACTOR = 33;
	int DEPFACTOR = 34;
	int COVFACTOR = 35;
	int FACTORLEVEL = 36;
	int CONDITIONTABLE = 37;
	int CONDITION = 38;
	int IMPORT = 39;
	int TRUE = 40;
	int FALSE = 41;
	int INTEGER_LITERAL = 42;
	int DECIMAL_LITERAL = 43;
	int HEX_LITERAL = 44;
	int FLOATING_POINT_LITERAL = 45;
	int EXPONENT = 46;
	int CHARACTER_LITERAL = 47;
	int STRING_LITERAL = 48;
	int IDENTIFIER = 49;
	int LETTER = 50;
	int DIGIT = 51;
	int DEFAULT = 0;
	int IN_SINGLE_LINE_COMMENT = 1;
	int IN_FORMAL_COMMENT = 2;
	int IN_MULTI_LINE_COMMENT = 3;
	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"",
			"\"\\f\"", "\"//\"", "<token of kind 7>", "\"/*\"",
			"<SINGLE_LINE_COMMENT>", "\"*/\"", "\"*/\"", "<token of kind 12>",
			"\"Experiment\"", "\"ExperimentData\"", "\"Procedure\"",
			"\"ProcedureEnd\"", "\"ProcedureData\"", "\"Session\"",
			"\"SessionEnd\"", "\"SessionData\"", "\"Block\"", "\"BlockEnd\"",
			"\"BlockData\"", "\"Trial\"", "\"TrialData\"", "\"new\"",
			"\"adjustable\"", "\"Context\"", "\"AssignmentGroup\"",
			"\"ContinuationGroup\"", "\"Factors\"", "\"RandomFactor\"",
			"\"IndependentFactor\"", "\"DependentFactor\"",
			"\"CovariateFactor\"", "\"FactorLevel\"", "\"ConditionTable\"",
			"\"Condition\"", "\"Import\"", "\"true\"", "\"false\"",
			"<INTEGER_LITERAL>", "<DECIMAL_LITERAL>", "<HEX_LITERAL>",
			"<FLOATING_POINT_LITERAL>", "<EXPONENT>", "<CHARACTER_LITERAL>",
			"<STRING_LITERAL>", "<IDENTIFIER>", "<LETTER>", "<DIGIT>", "\"{\"",
			"\"}\"", "\";\"", "\"(\"", "\",\"", "\")\"", "\".\"", "\"=\"",
			"\":\"", "\"?\"", "\"[\"", "\"]\"", "\"<\"", "\">\"",
			"\"de.pxlab.\"", "\"java.\"", "\"javax.\"", "\"+\"", "\"-\"",
			"\"||\"", "\"&&\"", "\"|\"", "\"^\"", "\"&\"", "\"==\"", "\"!=\"",
			"\"<=\"", "\">=\"", "\"<<\"", "\">>\"", "\">>>\"", "\"*\"",
			"\"/\"", "\"%\"", "\"~\"", "\"!\"", };
}
