package de.pxlab.pxl.gui;

import de.pxlab.pxl.display.*;

/**
 * The list of all available demo and experimental displays. Note that the demos
 * are mentioned here explicitely while the experimental displays are added via
 * an instance of ExperimentalDisplayCollection() which contains all
 * experimental displays.
 */
public class BigList extends DisplayCollection {
	public BigList() {
		this(0);
	}

	public BigList(int mask) {
		super(mask);
		/* List built on 2005/10/21 */
		/* Manual update: 2006/02/16 */
		/* Manual update: 2006/06/30 */
		add(new PXLabLogo());
		add(new VisionDemonstrationsLogo());
		add(new AdditiveColorMixer());
		add(new AdelsonPattern());
		add(new AdelsonPattern2());
		add(new AfterEffectImage());
		add(new AfterEffectPatch());
		add(new Anagram());
		add(new Arrow());
		add(new Assimilation());
		add(new Beep());
		add(new BenhamColorMixer());
		add(new BinaryRandomDotMatrix());
		add(new BlackSwitching());
		add(new BlockEndMessage());
		add(new BlockStartMessage());
		add(new BrightnessContrastInduction());
		add(new BrightnessInductionDisks());
		add(new BrightnessInductionSquares());
		add(new CIELabColorSampleSelection());
		add(new CIELabMaximumChroma());
		add(new CIELabPlane());
		add(new CenterSurroundWithFilter());
		add(new Chevron());
		add(new ChineseRings());
		add(new ChoiceResponse());
		add(new ClearScreen());
		add(new ClearScreenRandomTime());
		add(new CmdMessage());
		add(new CollinearGaborFest());
		add(new ColorCircleSelection());
		add(new ColorContrast());
		add(new ColorDiscrimination());
		add(new ColorFile());
		add(new ColorMeasurement());
		add(new ColorSampleSelection());
		add(new ColorSelection());
		add(new ColorSpectrum());
		add(new ColorStripes());
		add(new ColorTransformedPicture());
		add(new ColoredLine());
		add(new ColoredShadows());
		add(new ComplexColorContext());
		add(new ComplexColorContext2());
		add(new ComplexColorContextAnimated());
		add(new ConditionalWaitResponse());
		add(new ContractingBar());
		add(new Cornsweet());
		add(new CountDown());
		add(new Counter());
		add(new CrispeningEffect());
		add(new CrossContext3DMatching());
		add(new CrossContextMatching());
		add(new CrossContextMatchingMixed());
		add(new CrossContextMatchingRectMixed());
		add(new CuedLetterMatrix());
		add(new DINVideo1());
		add(new DINVideo2());
		add(new DarkAxes());
		add(new Desaturation());
		add(new DeuteranopicConfusionColors());
		add(new DeviceColorBar());
		add(new DeviceControl());
		add(new DeviceIntensitySteps());
		add(new DisplaySizeMeasurement());
		add(new DitherTest());
		add(new EquivalentBrightnessContext());
		add(new ErrorControl());
		add(new ExternalSignalOff());
		add(new ExternalSignalOn());
		add(new Feedback());
		add(new FifteenPuzzle());
		add(new FillScreen());
		add(new FillingIn());
		add(new FilteredMetamericSurfaces());
		add(new FixationMark());
		add(new FlickerMixer());
		add(new FlickeringBarsPhotometry());
		add(new FramedRod());
		add(new FramedSquares());
		// add(new GUIButton());
		// add(new GUILabel());
		add(new GaborFest());
		add(new GaborPattern());
		add(new GaborPatternAnimation());
		add(new GaussianFest());
		add(new GenericDisplay());
		add(new GeometricPath());
		add(new GeometrySearch());
		add(new GlowingAxes());
		add(new GrayLevels());
		add(new GrowingText());
		add(new HFHorLines());
		add(new HFVertLines());
		add(new HIStairs());
		add(new HVInterlace());
		add(new HVInterlace2());
		add(new HeadMotionInducedMotion());
		add(new HermannGrid());
		add(new HermannGridWithDots());
		// add(new HigherLevelAdap());
		add(new HomageToTheSquare());
		add(new HomageToTheSquare1());
		add(new HomageToTheSquare2());
		add(new HomageToTheSquare3());
		add(new HorizontalVerticalIllusion());
		add(new Hypersaturation());
		add(new IlluminationDeviceControl());
		add(new IlluminationDeviceControlDemo());
		add(new ImageFest());
		add(new IncrementCounter());
		add(new Induction());
		add(new InductionByAfterImage());
		add(new InductionMatching());
		add(new IncrementCounter());
		add(new Instruction());
		add(new ItemRanking());
		add(new Kanizsa());
		add(new KineticDepthPlane());
		add(new LFHorLines());
		add(new LFVertLines());
		add(new LIStairs());
		add(new LetterMatrix());
		add(new LetterMatrixFeedback());
		add(new LetterMatrixResponse());
		add(new LetterSearch());
		add(new LinAchStairs());
		add(new LinChStairs());
		add(new LinearSystem());
		add(new LookingGlass());
		add(new MCGame());
		add(new MacbethColorChecker());
		add(new MachBands());
		add(new MaskedArrow());
		add(new MaskedLetterMatrix());
		add(new MaxwellDisk());
		// add(new McCollough());
		add(new MediaPlayerOpen());
		add(new MediaPlayerStart());
		add(new MediaPlayerSync());
		add(new Message());
		add(new MetamericSurfaces());
		add(new MetamericSurfaces2());
		add(new MondrianMixturePattern());
		add(new MonochromaticOrdering());
		add(new Movie());
		add(new MovingDot());
		add(new MovingDotPair());
		add(new MuellerLyer());
		add(new MultipleChoiceQuestion());
		add(new MultipoleFest());
		add(new MunsellColorBar());
		add(new MunsellColorBoard());
		add(new MunsellColorSampleSelection());
		add(new MunsellConstantChroma());
		add(new MunsellConstantHue());
		add(new MunsellConstantValue());
		add(new MunsellMaximumChroma());
		add(new NavonPattern());
		add(new NeonColors());
		add(new Nothing());
		add(new OpponentColorsSuccessiveContrast());
		add(new OrderedFieldOfColors());
		// add(new PXLabLogo());
		add(new Picture());
		add(new PictureAnimation());
		// obsolete add(new PictureComparison());
		add(new PictureMasked());
		add(new PictureMatrix());
		// obsolete add(new PictureRating());
		add(new PlaidPattern());
		add(new PlaidPatternAnimation());
		add(new PointLightsAnimation());
		add(new PointLightsMixed());
		add(new PolyArea());
		add(new PowerSupplyTest());
		add(new ProtanopicConfusionColors());
		add(new PsychometricFunctionSimulator());
		add(new RandomColorSampleSelection());
		add(new RandomContextColorMatching());
		add(new RandomDotField());
		add(new RandomDotMotionContrast());
		add(new RandomDotMotionField());
		add(new RandomDotMotionThreshold());
		add(new RandomGenerator());
		add(new RandomNumberText());
		add(new RandomTilesColorDiscrimination());
		add(new RandomTilesColorVisionTest());
		add(new RandomTilesMask());
		add(new RapidSerialPresentation());
		add(new RatingScale());
		add(new ReadClock());
		add(new RectTest());
		add(new RedSquares());
		add(new ResponseControlCheck());
		add(new ResponseControlStart());
		add(new ResponseControlStop());
		add(new ResponseRobot());
		add(new SAM());
		add(new ScreenCapture());
		add(new SearchPattern());
		add(new SelfAssessmentManikin());
		add(new SerialLearningList());
		add(new SessionEndMessage());
		add(new SessionStartMessage());
		add(new SessionStateControl());
		add(new SetParameter());
		add(new ShowCIEWhitePoint());
		add(new SimpleBar());
		add(new SimpleCenterSurround());
		add(new SimpleDisk());
		add(new SimultanousBrightnessContrast());
		add(new SimultanousColorContrast());
		add(new SinusoidalGrating());
		add(new SinusoidalGratingImage());
		add(new Smiley());
		add(new SoundFile());
		add(new SoundRecorder());
		add(new SoundRecorderControl());
		add(new SpatialAttentionFrames());
		add(new SpatialAttentionTarget());
		add(new SpatialColorMixing());
		add(new SpatialColorRes());
		add(new SpatialMatching());
		add(new StartClock());
		add(new StripeInduction());
		add(new SyntheticSound());
		add(new SystemProcess());
		add(new TeemingPhotometry());
		add(new TextImage());
		add(new TextInput());
		add(new TextParagraph());
		add(new TextParagraphComposed());
		add(new TextParagraphMultiple());
		add(new TimingGroupsTest());
		add(new Todorovic2());
		add(new TodorovicFigure());
		add(new TowerOfHanoi());
		add(new TrackingTarget());
		add(new TrialMessage());
		add(new Trigger());
		add(new TritanopicConfusionColors());
		add(new TwoColorImageProjection());
		add(new TwoIlluminants());
		add(new TwoStrings());
		add(new VierGewinnt());
		// add(new VisionDemonstrationsLogo());
		add(new VisualGammaBlue());
		add(new VisualGammaGreen());
		add(new VisualGammaRed());
		add(new VisualGammaTarget());
		add(new VoiceKey());
		add(new WaterJugs());
		add(new WertheimerBar());
		add(new WertheimerBenary());
		add(new WhiteSwitching());
		add(new WhitesIllusion());
		/*
		 * if (isApplication) addPlugins("plugins");
		 */
		trimToSize();
	}
}
